### ISSUE TITLE
Make external dependencies optional

### ISSUE THREAD

**Issue by ilyanoskov** [pathwaycom/pathway#16]
Hello, do you think it's possible to make some of the external dependencies optional for Pathway?

Things like:
- google-api-python-client
- Office365-REST-Python-Client

or anything else that the end users might not actually need to run Pathway? In my personal case, I never intend to use google-api or Office365 and I don't want to bring these dependencies in my Python project. I think it makes sense if these become optional / installable separately?

**Comment by dxtrous** [comment]
Thanks for bringing this up. Providing package extras that would allow e.g. `pip install pathway[no-xpacks]` with a minimum set of dependencies is on the roadmap.
Keeping this one open until it happens.

**Comment by dxtrous** [comment]
Closing as done - xpacks support has been around for a while now and is mature.
