### ISSUE TITLE
[QUESTION]: Pathway support for custom AirByte connector?

### ISSUE THREAD

**Issue by vikassinghvi2007** [pathwaycom/pathway#24]
Question:
If we were to build a custom AirByte source connector, would it get automatically supported on Pathway via AirByte Serverless? If not, what would be the turn around time for support via Pathway? Also, would there be additional work on our side towards AirByte Serverless/ PyAirByte or to use Pathway?

**Comment by dxtrous** [comment]
Hi @vikassinghvi2007 Yes, if you build and package your own Airbyte connector in the package format used by Airbyte Serverless, it will be ready for use by Pathway as-is, following the provided installation instructions. So e.g. forking one of the existing connectors and modifying it will work.

If your only objective is to get the connector running in Pathway, a lighter alternative is to implement the few required connectors methods directly in Python - here are two approaches and example, for Twitter API and for Polygon:
https://pathway.com/developers/user-guide/connectors/custom-python-connectors/
https://pathway.com/developers/user-guide/connectors/websockets-connectors
You can also use Pathway to expose a REST endpoint (not client):
https://pathway.com/developers/api-docs/pathway-io/http/#pathway.io.http.rest_connector

**Comment by dxtrous** [comment]
@vikassinghvi2007 by all means, and happy to help out if needed!

**Comment by vikassinghvi2007** [comment]
Awesome, thank you so much!
