### ISSUE TITLE
[Bug]: Slow pip dependencies - wheels building for python-sat and others

### ISSUE THREAD

**Issue by dxtrous** [pathwaycom/pathway#26]
### Steps to reproduce

Today, fresh Pathway installations from pip are taking rather long minutes rather than the usual 35 seconds (Colab timings).
I would propose to fix this as a priority.

### Relevant log output

```text
Pip takes most time on: `Building wheels for collected packages: python-sat`.
```

### What did you expect to happen?

No wheels built from sources

### Version

0.8.4

### OS

Linux

### On which CPU architecture did you run Pathway?

None

**Comment by embe-pw** [comment]
This usually happens just after a new release, when the wheels are not yet built.
Usually resolves itself in around a day.
We usually pass `--prefer-binary` to `pip install` so that vwrsions with wheels missing are skipped.

**Comment by dxtrous** [comment]
Thanks @embe-pw.
@olruas in that case perhaps we could change model instructions for Colab at least to `--prefer-binary`, wdyt?

**Comment by olruas** [comment]
Good idea @dxtrous.

**Comment by olruas** [comment]
The change is done: the notebooks now have the `--prefer-binary` option and the installation is back to something similar to what we had before.
