### ISSUE TITLE
Set up GitHub action to run tests

### ISSUE THREAD

**Issue by swarajpande5** [pathwaycom/pathway#3]
Set up GitHub action to do automated testing of [pathway](https://github.com/pathwaycom/pathway) codebase, whenever a PR is submitted for `main` branch of the repository.

- [ ] Rust tests (via Cargo)
- [ ] Python tests (via Pytest)

Later [codecov](https://about.codecov.io/) and other linting checks can be added for better visibility.

I would love to work on this.

**Comment by janchorowski** [comment]
Hi @swarajpande4 we are using `pytest` and `cargo tests` internally, but miss the infrastructure for public testing of PRs and any support will be appreciated!

**Comment by janchorowski** [comment]
The repo is re-tested and test results are visible in readme badges.
