### ISSUE TITLE
I want to convert a dict inside list  into table with key as column name 

### ISSUE THREAD

**Issue by abdul756** [pathwaycom/pathway#30]
**What is your question or problem? Please describe.**
How to  convert a dict inside list  into table with key as column name 

**Describe what you would like to happen**
response = [
                 "key 1" : "abcc"
                 "key 2": "efgh"
]

I want to convert response to table
table = "key 1"  |  "key 2"
              "abcc"        "efgh"
Please help to achieve this

**Comment by zxqfd555-pw** [comment]
Hi @abdul756

To create such kinds of tables we have several functions in the `pw.debug` module. Please refer to the docs [here](https://pathway.com/developers/api-docs/debug/).

In particular, you can use the [table_from_pandas](https://pathway.com/developers/api-docs/debug/#pathway.debug.table_from_pandas) method which creates a table from Pandas object where you can form a table object as you need. In the adjacent docs, there are some usage examples for this method, for instance, [here](https://pathway.com/developers/api-docs/pathway-table#pathway.Table.plot).

**Comment by abdul756** [comment]
Thank you

**Comment by abdul756** [comment]
Thank you its working
