### ISSUE TITLE
how to change sync mode from incremental to full refresh

### ISSUE THREAD

**Issue by xHishamSaeedx** [pathwaycom/pathway#37]
this is the code i am trying to execute 

    import pathway as pw
    
    issues_table = pw.io.airbyte.read(
        "./connections/github.yaml",
        streams=["tags"],
    )
    
    pw.io.jsonlines.write(issues_table, "issues.jsonlines")
    
    pw.run()

and this is the error i am receiving 

      Traceback (most recent call last):
        File "/home/hisham/Documents/GitHub/github-service/github.py", line 3, in <module>
          issues_table = pw.io.airbyte.read(
        File "/usr/local/lib/python3.10/dist-packages/pathway/io/airbyte/__init__.py", line 280, in read
          raise ValueError(f"Stream {name} doesn't support 'incremental' sync mode")
      ValueError: Stream tags doesn't support 'incremental' sync mode

how do i change the sync mode ??

**Comment by KamilPiechowiak** [comment]
Hey @xHishamSaeedx,
Currently, the airbyte connector supports only `incremental` mode (see the [docs](https://pathway.com/developers/api-docs/pathway-io/airbyte)). The `full refresh` mode is planned but not yet available.

**Comment by xHishamSaeedx** [comment]
ok thanks!
