### ISSUE TITLE
Allow sending columns with raw bytes in the python connector

### ISSUE THREAD

**Issue by lewymati** [pathwaycom/pathway#39]
**Is your feature request related to a problem? Please describe.**
Cannot stream a table with multiple columns via a Python connector, when one of them is of type `bytes`. For example:
```python
message = {"col1": "foo", "col2": some_bytes}
self.next_json(message)
```
doesn't work as bytes are not json serializable.
`self.next_bytes` is not useful as well as it expects bytes encoded *json string*.

Some workaround is to use base64 to serialize/deserialize, but it's not ideal.

**Comment by KamilPiechowiak** [comment]
Passing column with type `bytes` is supported since version `0.11.2`. You can use `next` method of the `pw.io.python.ConnectorSubject` for that:
```python
self.next(col1="foo", col2=some_bytes)
```
Passing `bytes` with `next_json` won't work as it expects the content to be json-serializable.
