### ISSUE TITLE
[Bug]: Reproduction of Twitter's Custom Python Connector code encours Auth issues

### ISSUE THREAD

**Issue by TaufeeqNoamaan** [pathwaycom/pathway#43]
### Steps to reproduce

I've used the code directly from the Python Custom Connector example as give below:
[Code](https://github.com/pathwaycom/pathway/tree/main/examples/projects/custom-python-connector-twitter)

There's a constant Authentication issue when I use the BEARER_TOKEN generated directly from Twitter's API dashboard.

_I'm using the default project and the default app generated by twitter upon signing-up for free tier_

### Relevant log output

```text
When use BEARER TOKEN following is the log-output on dashboard:

Stream encountered HTTP error: 403                                                                                                                    
                      ERROR    HTTP error response text: {"client_id":"28689517","detail":"When authenticating requests to the Twitter API v2 endpoints, you must use keys and       
                               tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer                                         
                               portal.","registration_url":"https://developer.twitter.com/en/docs/projects/overview","title":"Client Forbidden","required_enrollment":"Appropriate   
                               Level of API Access","reason":"client-not-enrolled","type":"https://api.twitter.com/2/problems/client-forbidden"}
```

### What did you expect to happen?

Expected to run without any AUTH issues

### Version

0.9.0

### OS

Linux

### On which CPU architecture did you run Pathway?

x86-64

**Comment by voodoo11** [comment]
Thanks for reporting. This is not really an issue with Pathway. It seems that Twitter API has changed, and streaming endpoints are no longer available, at least in the free tier.
