### ISSUE TITLE
Adjust examples using Twitter API

### ISSUE THREAD

**Issue by voodoo11** [pathwaycom/pathway#44]
As turned out in https://github.com/pathwaycom/pathway/issues/43, Twitter streaming API is no longer working. 

We should adjust examples:
https://pathway.com/developers/user-guide/connectors/custom-python-connectors
https://github.com/pathwaycom/pathway/tree/main/examples/projects/custom-python-connector-twitter

**Comment by dxtrous** [comment]
@voodoo11 A minimum fix has been rolled out, ready to close?
