### ISSUE TITLE
Private Rag Example not working

### ISSUE THREAD

**Issue by XamHans** [pathwaycom/pathway#51]
I am following the steps provided in the example (https://github.com/pathwaycom/llm-app/tree/main/examples/pipelines/private-rag)
When I execute the curl command to test it, I get this error:
`
```
thread 'pathway:work-0' panicked at src/engine/report_error.rs:152:14:
APIConnectionError: 'name'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/hans/youtube-videos/pathway-demo/app.py", line 72, in <module>
    app.run_server(with_cache=True)
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pathway/xpacks/llm/question_answering.py", line 488, in run_server
    pw.run(
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pathway/internals/runtime_type_check.py", line 19, in with_type_validation
    return beartype.beartype(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(pathway.internals.run.run) at 0x7f60afa1c5e0>", line 147, in run
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pathway/internals/run.py", line 51, in run
    ).run_outputs()
      ^^^^^^^^^^^^^
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pathway/internals/graph_runner/__init__.py", line 118, in run_outputs
    self.run_nodes(self._graph.global_scope.output_nodes, after_build=after_build)
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pathway/internals/graph_runner/__init__.py", line 94, in run_nodes
    self._run(all_nodes, after_build=after_build)
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pathway/internals/graph_runner/__init__.py", line 224, in _run
    raise error from None
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pathway/internals/udfs/utils.py", line 34, in wrapper
    return await event_loop.run_in_executor(None, func=pfunc)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pathway/xpacks/llm/llms.py", line 312, in __wrapped__
    ret = litellm.completion(
          ^^^^^^^^^^^^^^^^^^^
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/litellm/utils.py", line 3317, in wrapper
    raise e
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/litellm/utils.py", line 3211, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/litellm/main.py", line 2365, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/litellm/utils.py", line 9666, in exception_type
    raise e
  File "/home/hans/.pyenv/versions/3.11.6/lib/python3.11/site-packages/litellm/utils.py", line 9641, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: 'name'
```
---------
I can see that the query is send to the LiteLLM

```
POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:11434/api/generate \
-d '{'model': 'mistral', 'prompt': '\ '\n        Use the below articles to answer the subsequent question. If the answer cannot be found in the articles, write "No information available." Do not explain.\n        ONLY RESPOND IN PARSABLE JSON WITH THE ONLY KEY `answer`.\n        When referencing information from a source, cite th.....` 
```

**Comment by izulin** [comment]
Thanks for the bugreport, we're investigating.

**Comment by berkecanrizai** [comment]
Hi @XamHans, what version of Ollama are you using?
Can you confirm that you can reach to local model with the following query:
```bash
curl -X POST http://localhost:11434/api/generate -d '{
  "model": "mistral",
  "prompt":"Here is a story about llamas eating grass"
 }'
```

Another user had a similar issue with a different model because the model wasn't supporting `json` format, could you try the following query:

```bash
curl http://localhost:11434/api/generate -d '{
  "model": "mistral",
  "prompt": "What is the ticker symbol for Meta? Respond with JSON where the key is the company name.",
  "format": "json"
}'
```

If the second query fails, you can try updating the Ollama or removing the `format="json",` argument in the `chat = llms.LiteLLMChat` LLM instance. Hope this helps.

**Comment by XamHans** [comment]
Hi i am using latest Ollama version(1.38)

Yeah when I make this request (
```
curl -X POST http://localhost:11434/api/generate -d '{
  "model": "mistral",
  "prompt":"Here is a story about llamas eating grass"
 }'
```
I get this response:
.....
{"model":"mistral","created_at":"2024-05-17T10:59:17.130830624Z","response":"{\"","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.217418473Z","response":"ing","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.23357285Z","response":" sight","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.249819149Z","response":",","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.265896296Z","response":" they","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.282012739Z","response":" couldn","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.298167988Z","response":"'","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.314329085Z","response":"t","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.330497001Z","response":" help","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.346756222Z","response":" but","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.363026708Z","response":" be","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.379193535Z","response":" reminded","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.395402257Z","response":" of","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.411534101Z","response":" the","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.427667522Z","response":" simple","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.443813165Z","response":" jo","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.459889094Z","response":"ys","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.476193264Z","response":" of","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.492776835Z","response":" life","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.508995765Z","response":",","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.525187041Z","response":" a","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.54172483Z","response":" lesson","done":false}
....
{"model":"mistral","created_at":"2024-05-17T10:59:34.688016413Z","response":" today","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.704510287Z","response":".","done":false}
{"model":"mistral","created_at":"2024-05-17T10:59:34.720834252Z","response":"","done":true,"done_reason":"stop","context":[733,16289,28793,28705,4003,349,264,2838,684,17620,293,8652,10109,733,28748,16289,28793,13623,28747,415,393,28714,2786,420,5237,404,13,13,16114,3714,264,727,28725,297,272,305,1426,304,5344,1486,5603,302,272,1015,274,26425,28725,736,403,264,25444,6435,970,17620,293,712,3000,21964,28723,851,8310,1011,6435,28725,17875,1006,22574,303,272,15483,18553,28725,403,2651,354,871,13546,440,5679,304,272,10434,5220,1549,369,1987,378,1611,28723,13,13,1014,4314,9535,18707,1497,652,559,3673,302,17620,293,28725,690,4226,264,12588,3905,297,652,6790,4621,28723,393,5989,293,654,459,865,652,21708,24804,562,835,652,6258,2832,302,8131,269,617,28723,415,6435,3289,286,356,272,8814,2786,25943,354,21606,1938,272,484,7915,1015,28706,276,3108,1532,304,1307,652,2967,304,341,324,4689,15806,298,6209,11282,2673,272,13644,2560,21945,28723,13,13,2198,272,907,408,748,302,22950,847,2701,272,1015,28706,276,13894,28725,272,4314,9535,682,11088,582,298,272,27043,294,1997,28713,302,12780,304,272,10434,14912,1905,302,10109,28723,415,17620,293,28725,3564,288,272,1721,302,16678,28725,682,2839,652,6790,11935,387,27004,288,297,272,18070,440,2609,1238,369,18612,286,272,17682,21264,28723,13,13,1014,6435,639,10802,553,1043,8324,369,9836,652,17620,293,298,18216,1374,21964,356,272,305,1426,10109,5603,459,865,4558,706,7783,562,835,3956,2330,396,15116,440,8109,1430,879,28723,415,17620,293,28725,395,652,717,546,9401,304,1043,7215,28713,28725,682,13754,3071,25527,1060,298,307,593,982,438,272,20602,6041,28713,28725,6285,2910,776,2066,341,12542,354,983,671,362,28723,851,5245,403,264,3659,2757,302,19318,25209,764,264,4297,6309,7839,3758,1444,10589,304,4735,369,553,750,1404,2967,354,16806,28723,13,13,2198,272,17620,293,27004,286,28725,590,682,14200,297,2664,17256,395,624,1698,28725,652,14549,843,2570,26739,7990,395,272,10434,7258,302,272,5535,9502,288,1059,272,7099,28723,415,4314,9535,682,2608,5175,706,1938,652,528,2304,1198,28725,10681,5979,304,18211,390,590,6758,652,21708,18349,306,6016,297,652,4229,20878,28723,13,13,1014,6435,403,264,4672,20521,302,9097,28725,11755,2437,28725,304,19511,28725,544,4248,684,486,272,3588,2783,19327,960,302,17620,293,8652,10109,28723,851,6790,6337,302,3618,28725,2016,354,4735,28725,304,3116,354,8222,11971,12085,477,2082,304,5335,298,1038,272,8123,582,298,272,1015,28706,276,1486,5603,28723,1136,590,27778,286,438,456,481,11746,288,7739,28725,590,3481,28742,28707,1316,562,347,14795,302,272,3588,5821,846,302,1411,28725,264,15330,369,10352,298,16379,380,395,592,544,3154,28723],"total_duration":8414883623,"load_duration":853964,"prompt_eval_count":13,"prompt_eval_duration":374866000,"eval_count":504,"eval_duration":7993505000}

With this request:
```
curl http://localhost:11434/api/generate -d '{
  "model": "mistral",
  "prompt": "What is the ticker symbol for Meta? Respond with JSON where the key is the company name.",
  "format": "json"
}'
```
I get the same as before but without the ending (embeddings) part

**Comment by berkecanrizai** [comment]
Could you try updating Pathway to `0.11.1` and checking your LiteLLM version with `pip show litellm`?
LiteLLM should be `1.35.12`. Please try with these versions.

I just ran it on Ollama `0.1.38` without any issue with the above setup.

If that doesn't help, could you try commenting out the `format="json",` and see if anything changes?

Could you share your setup (OS, Docker, etc.)?

**Comment by XamHans** [comment]
Hi @berkecanrizai 

Thanks for your help and quick response ! Indeed downgrading litellm to version 1.35.12 worked! Thanks

Can we add a requirements.txt to the project with your provided versions to that other people dont have this struggle ?
