### ISSUE TITLE
[Bug]: *Table desugaring + *.ix(pw.this) desugaring fails

### ISSUE THREAD

**Issue by izulin** [pathwaycom/pathway#52]
### Steps to reproduce

this explodes:
`        bar = foo.with_columns(*(data.ix(pw.this.ids)[["a", "b"]]))`

but this works:
`        bar = foo.with_columns(*(data.ix(foo.ids)[["a", "b"]]))`

and this also works:
`        bar = foo.with_columns(data.ix(pw.this.ids).a, data.ix(pw.this.ids).b))`

### Relevant log output

```text
-
```

### What did you expect to happen?

-

### Version

0.11.0

### OS

Linux

### On which CPU architecture did you run Pathway?

None

**Comment by voodoo11** [comment]
Fixed in 0.11.2
