### ISSUE TITLE
The integrated feature processing and consistency validation of batch and stream processing

### ISSUE THREAD

**Issue by graceyangfan** [pathwaycom/pathway#78]
I am trying to implement a feature processing solution for both batch and stream processing, and a challenging issue is that I need to build separate operators for offline and online processing. I noticed that the project mentions the possibility of implementing feature extraction for both batch and stream processing. However, I am unsure whether there has been any comparison of the results between batch and stream processing for consistency. Will the example provided also consider cases where offline batch processing is used for training models, while online stream processing is used for deployment?"

**Comment by KamilPiechowiak** [comment]
Hey @graceyangfan.
What is the logic that you're trying to implement? What problems did you encounter while trying to use the same logic for batch and streaming processing modes?

> Will the example provided (...)?

What example are you referring to?

**Comment by graceyangfan** [comment]
@KamilPiechowiak This is just my idea, and it might be quite challenging to implement. The approach would involve using batch processing during training and switching to streaming mode for prediction during deployment. This means ensuring the API remains unchanged while achieving consistent computation results across batch and streaming modes. To accomplish this, support for UDF (User-Defined Functions) is required, and ideally, the logic should be defined once and be compatible with both batch and streaming modes simultaneously..I’m not sure if it’s possible at this stage to implement a simple example of such a workflow.

**Comment by KamilPiechowiak** [comment]
Hey @graceyangfan,
I am not sure if I understand what you want to achieve.
I understand that you would like to use a single pipeline with a separate logic for batch and stream processing, right? You could achieve something similar by using two separate pipelines that would share most of the logic but would differ in some places. Then you would reduce code duplication and could run one pipeline in batch mode and one pipeline in streaming mode.

If you would like to use exactly one pipeline, it is also possible. However, you should think if you really need it. It makes sense to run it in such a way if you want to train your model online - simultaneously with answering queries. But if you already have all data you want to train your model on, you can use two pipelines solution described above. Then you would run training batch pipeline first and streaming inference pipeline second.

You mentioned, you need support for UDFs. Pathway supports them, see [the UDF tutorial](https://pathway.com/developers/user-guide/data-transformation/user-defined-functions).

Feel free to reopen, if you want to provide more details/ask more questions.
